/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lekce204;

import java.awt.Color;
import java.awt.GridLayout;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.JTextField;

/**
 *
 * @author vojta
 */
public class Matrix extends javax.swing.JFrame {

    private int col = 5;//sloupce
    private int rows = 5;//radky
    private JTextField[][] fields = new JTextField[rows][col];//vytvoreni poli 5x5
    
    /**
     * Creates new form Matrix
     */
    
    public Matrix() {//konstruktor
        initComponents();
        setupMatrix();
    }
    
    private void setupMatrix(){//nastvaeni matrixu a setup gridu
        setLayout(new GridLayout(rows, col));
        
        for(int i = 0; i < rows; i++){
            for(int j = 0; j < col; j++){
                JTextField tf = new JTextField();
                
                tf.setBackground(Color.WHITE);
                tf.addFocusListener(new FieldFocus());
                tf.addKeyListener(new FieldKeys());
                fields[i][j] = tf;
                add(tf);
            }
        }
        pack();
    }
    
    private class FieldFocus implements FocusListener{//kdyz bunka dostane focus

        @Override//prepsana metoda
        public void focusGained(FocusEvent e) {//focus je ziskany
            JTextField tf = (JTextField) e.getSource();//jaka bunka
            
            tf.setBackground(Color.YELLOW);//prenstavy barvu na zlutou
        }

        @Override//prepsana metoda
        public void focusLost(FocusEvent e) {//focus ztracen
            JTextField tf = (JTextField) e.getSource();//jaka bunka
            
            if(tf.getText().trim().isEmpty()){
                tf.setBackground(Color.WHITE);
                tf.setEnabled(true);
            } else{
                tf.setBackground(Color.DARK_GRAY);
                tf.setEnabled(false);
            }
        }
    }
    
    private class FieldKeys extends KeyAdapter{
        @Override
        public void keyPressed(KeyEvent e) {
            JTextField source = (JTextField) e.getSource();
            
            if(e.getKeyCode() == KeyEvent.VK_ENTER){
                transposeMatrix();
            }
            if(e.getKeyCode() == KeyEvent.VK_ESCAPE){
                resetMatrix(source);
            }
        }
    }
    
    private void transposeMatrix(){
        String[][] values = new String[rows][col];
        
        for(int i = 0; i < rows; i++){
            for(int j = 0; j < col; j++){
                values[i][j] = fields[i][j].getText();
            }
        }
        
        for(int i = 0; i < rows; i++){
            for(int j = 0; j < col; j++){
                fields[i][j].setText(values[j][i]);
            }
        }
    }
    
    private void resetMatrix(JTextField keepYellow){
        for(int i = 0; i < rows; i++){
            for(int j = 0; j < col; j++){
                fields[i][j].setEnabled(true);
                fields[i][j].setBackground(Color.WHITE);
                fields[i][j].setText("");
            }
        }
        keepYellow.setBackground(Color.YELLOW);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Matrix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Matrix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Matrix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Matrix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Matrix().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}